// English bimbofy data: phrase swaps, sentence insertions, numbers, dictionary, and typo rules.
export const EN_BIMBOFY_DATA = {
   normalizeQuotes: true,
   "phrases": [
      { "phrase": "kind of", "replacements": ["kinda", "sorta", "like kinda"], "probability": 0.35 },
      { "phrase": "a lot", "replacements": ["alot", "like a lot", "sooo much"], "probability": 0.35 },
      { "phrase": "I am", "replacements": ["I'm", "me is", "I is"], "probability": 0.25 },
      { "phrase": "you know", "replacements": ["ya know", "you knowww", "like y'know"], "probability": 0.3 },
      { "phrase": "I think", "replacements": ["I like think", "me thinks", "I totes think"], "probability": 0.32 },
      { "phrase": "right now", "replacements": ["right nowww", "like rn", "right this second"], "probability": 0.28 },
      { "phrase": "of course", "replacements": ["obvi", "of courseee", "duh"], "probability": 0.33 },
      { "phrase": "I don't know", "replacements": ["idk", "I dunno", "like no ideaaa"], "probability": 0.4 },
      { "phrase": "really", "replacements": ["rly", "like reallyyy", "for reals"], "probability": 0.35 },
      { "phrase": "oh my god", "replacements": ["omg", "oh em gee", "like omggg"], "probability": 0.45 },
      { "phrase": "for sure", "replacements": ["fasho", "for suuure", "totally"], "probability": 0.3 },
      { "phrase": "I like", "replacements": ["I likee", "me like", "I so like"], "probability": 0.28 },
      { "phrase": "maybe", "replacements": ["maybs", "like maybeee", "probz"], "probability": 0.32 },
      { "phrase": "what do you think", "replacements": ["what do ya think", "whatcha think", "like what do u thinkkk"], "probability": 0.27 },
      { "phrase": "very good", "replacements": ["sooo good", "like super good", "amazinggg"], "probability": 0.3 },
      { "phrase": "let's go", "replacements": ["lets gooo", "like let's gooo", "we go"], "probability": 0.25 },
      { "phrase": "I want", "replacements": ["I wanttt", "me wants", "I sooo want"], "probability": 0.35 },
      { "phrase": "you are", "replacements": ["u r", "you is", "ya are"], "probability": 0.3 },
      { "phrase": "so cute", "replacements": ["sooo cute", "like super cute", "adorbs"], "probability": 0.38 },
      { "phrase": "I love it", "replacements": ["I luv it", "me loveees", "like omg I loveee"], "probability": 0.4 },
      { "phrase": "totally", "replacements": ["totes", "totallyyy", "like totes"], "probability": 0.33 },
      { "phrase": "oh yeah", "replacements": ["oh yaaas", "oh yeaaah", "like oh yeahhh"], "probability": 0.3 },
      { "phrase": "come on", "replacements": ["c'mon", "like come onnn", "commm on"], "probability": 0.28 },
      { "phrase": "that's hot", "replacements": ["thats so hot", "like sooo hot", "thats hawt"], "probability": 0.35 }
   ],
   sentence: {
      minWords: 4,
      insertions: [
         {
            position: "tail",
            minWords: 6,
            probability: 0.35,
            values: ["and stuff", "or whatever", "you know"]
         },
         {
            position: "prefix",
            probability: 0.22,
            values: ["So, ", "Like, ", "Um, "]
         },
         {
            position: "beforeWord",
            minWordLength: 4,
            probability: 0.25,
            values: ["basically", "totally", "kinda"]
         }
      ]
   },
   numberLabels: {
      many: "lots"
   },
   wordTransform: {
      dictionaryProbability: 0.5,
      ruleProbability: 0.5,
      simplePlural: true,
      simplePluralReplacement: /^[a-z]+$/,
      collapseRepeatedLetters: true,
      repeatedLetterPattern: /[a-z]/i
   },
   misspellRules: [
      { pattern: /bility\b/g, replacement: "ilty", probability: 0.35 },
      { pattern: /tible\b/g, replacement: "tidle", probability: 0.25 },
      { pattern: /ces\b/g, replacement: "cies", probability: 0.25 },
      { pattern: /ges\b/g, replacement: "gies", probability: 0.25 },
      { pattern: /\bth(?!i)/g, replacement: "d", probability: 0.4 },
      { pattern: /ph\B/g, replacement: "f", probability: 0.35 },
      { pattern: /ee/g, replacement: "ea", probability: 0.3 },
      { pattern: /ou/g, replacement: "u", probability: 0.25 },
      { pattern: /([sv])e\b/g, replacement: "$1", probability: 0.25 },
      { pattern: /([b-df-hj-npv-z])r\B/g, replacement: "$1w", probability: 0.2 },
      { pattern: /s\b/g, replacement: "z", probability: 0.4 },

      // Новые правила (добавил 18 штук)
      { "pattern": /ing\b/g, "replacement": "in'", "probability": 0.35 },
      { "pattern": /er\b/g, "replacement": "ah", "probability": 0.3 },
      { "pattern": /ed\b/g, "replacement": "d", "probability": 0.32 },
      { "pattern": /ck/g, "replacement": "k", "probability": 0.28 },
      { "pattern": /ai/g, "replacement": "ay", "probability": 0.25 },
      { "pattern": /ea/g, "replacement": "ee", "probability": 0.22 },
      { "pattern": /([aeiou])t\b/g, "replacement": "$1dd", "probability": 0.3 },
      { "pattern": /([aeiou])l\b/g, "replacement": "$1ll", "probability": 0.35 },
      { "pattern": /([aeiou])m\b/g, "replacement": "$1mm", "probability": 0.28 },
      { "pattern": /([aeiou])n\b/g, "replacement": "$1nn", "probability": 0.32 },
      { "pattern": /\bmy/g, "replacement": "mah", "probability": 0.25 },
      { "pattern": /\byou/g, "replacement": "ya", "probability": 0.4 },
      { "pattern": /\bthe/g, "replacement": "da", "probability": 0.35 },
      { "pattern": /([aeiou])r([aeiou])/g, "replacement": "$1w$2", "probability": 0.3 },
      { "pattern": /([aeiou]{2,})/g, "replacement": "$1$1", "probability": 0.2 },
      { "pattern": /([a-z])\1{2,}/g, "replacement": "$1$1", "probability": 0.25 },
      { "pattern": /love/g, "replacement": "luv", "probability": 0.45 },
      { "pattern": /fuck/g, "replacement": "fck", "probability": 0.15 },
      { "pattern": /very/g, "replacement": "verry", "probability": 0.3 },
      { "pattern": /really/g, "replacement": "rly", "probability": 0.38 },
      { "pattern": /like/g, "replacement": "lyke", "probability": 0.25 },
      { "pattern": /what/g, "replacement": "wut", "probability": 0.35 },
      { "pattern": /girl/g, "replacement": "gurl", "probability": 0.4 },
      { "pattern": /baby/g, "replacement": "babii", "probability": 0.32 }
   ],
   "words": {
      "about": ["abat", "abaut"],
      "actually": ["actauly", "actuali", "actualy"],
      "anonymous": ["anonymus", "anynomous"],
      "am": [{ "synonym": "are" }],
      "are": [{ "spelling": "is", "weight": 1 }, { "spelling": "are", "weight": 1 }],
      "basically": ["baesicly", "basicaly", "basicly"],
      "college": ["collage"],
      "computer": ["comptuer", "computr"],
      "could": ["cudd"],
      "development": ["delevopment"],
      "doctor": ["doc"],
      "favorite": ["fav"],
      "fewer": ["fewer", "less"],
      "further": [{ "synonym": "farther" }],
      "game": ["gaem", "gam"],
      "is": [{ "synonym": "are" }],
      "know": ["knw", "konw", "nkow"],
      "large": ["big", "huge"],
      "less": [{ "synonym": "fewer" }],
      "library": ["libary"],
      "like": ["like"],
      "love": ["<3", "luv", "lve"],
      "next": ["enxt", "nex"],
      "ok": ["oki", "okee"],
      "okay": [{ "synonym": "ok" }],
      "okey": [{ "synonym": "ok" }],
      "photo": [{ "synonym": "picture" }],
      "picture": ["pic"],
      "probably": ["probly", "prolly"],
      "room": [{ "spelling": "room", "weight": 10 }, { "spelling": "roo", "weight": 1 }],
      "should": ["should", "shud"],
      "so": ["so", "soo", "sooo"],
      "take": ["taek", "tak"],
      "than": ["than", "then"],
      "the": [{ "spelling": "thi", "weight": 1 }, { "spelling": "dee", "weight": 1 }, { "spelling": "de", "weight": 1 }],
      "then": [{ "synonym": "than" }],
      "these": ["dese", "deze"],
      "thus": [{ "synonym": "so" }],
      "university": ["uni"],
      "very": ["sooo", "like super", { "spelling": "verry", "weight": 0.6 }],
      "video": ["vid"],
      "was": ["were"],
      "were": ["was"],
      "whatever": ["whatevs"],
      "who": ["hu"],
      "would": ["wudd"],
      "you": [{ "spelling": "ya", "weight": 1 }, { "spelling": "yah", "weight": 1 }, { "spelling": "u", "weight": 1 }],
      "woman": ["girl", "bimbo", "doll"],
      "sexy": ["sexxxy", "hawt", "hottt"],
      "cute": ["cutie", "adorbs", "sooo cute"],
      "now": ["nowww", "rn", "right nowww"]
   }
};
