// Russian bimbofy data: compact Russian-specific phrases, fillers, typo rules, and dictionary entries.
export const RU_BIMBOFY_DATA = {
   "phrases": [
      { "phrase": "потому что", "replacements": ["патамушта", "потому что типа", "нууу патаму"], "probability": 0.42 },
      { "phrase": "как будто", "replacements": ["как буто", "как будто типа", "как бы типа"], "probability": 0.35 },
      { "phrase": "на самом деле", "replacements": ["ваще-то", "на самом деле типа", "нууу ваще"], "probability": 0.34 },
      { "phrase": "в общем", "replacements": ["вообщем", "кароче", "нууу в общем"], "probability": 0.36 },
      { "phrase": "я думаю", "replacements": ["мне кажется", "я думаю типа", "нууу я думаю"], "probability": 0.24 },
      { "phrase": "не знаю", "replacements": ["не знаааю", "нууу не знаю", "без понятия"], "probability": 0.4 },
      { "phrase": "сейчас", "replacements": ["щас", "щааас", "прямо сейчас"], "probability": 0.38 },
      { "phrase": "конечно", "replacements": ["канешно", "конешнооо", "нууу канеш"], "probability": 0.37 },
      { "phrase": "очень хорошо", "replacements": ["очень-преочень", "так хорошооо", "ваааще норм"], "probability": 0.33 },
      { "phrase": "я хочу", "replacements": ["хачу", "я так хачу", "мне очень хочется"], "probability": 0.35 },
      { "phrase": "ты такой", "replacements": ["ты такооой", "ты такой милый", "ты такой горячий"], "probability": 0.32 },
      { "phrase": "боже мой", "replacements": ["божечки", "ой блин", "нууу боже"], "probability": 0.4 },
      { "phrase": "точно", "replacements": ["точнооо", "100%", "нууу точно"], "probability": 0.3 },
      { "phrase": "мне нравится", "replacements": ["мне нравица", "так нравицца", "я тащусь"], "probability": 0.35 },
      { "phrase": "давай", "replacements": ["давааай", "погнали", "нууу давай"], "probability": 0.28 },
      { "phrase": "я не могу", "replacements": ["я не могууу", "не могууу", "нууу я не могу"], "probability": 0.32 },
      { "phrase": "так мило", "replacements": ["так миииило", "кааак мило", "просто прелесть"], "probability": 0.38 },
      { "phrase": "серьезно", "replacements": ["сириозна", "серьезнааа", "нууу серьезно"], "probability": 0.3 },
      { "phrase": "привет", "replacements": ["приветик", "хейй", "превед"], "probability": 0.4 },
      { "phrase": "спасибо", "replacements": ["спс", "пасибааа", "оочень спасибо"], "probability": 0.35 },
      { "phrase": "ладно", "replacements": ["ладнооо", "нууу ладно", "окейчики"], "probability": 0.33 },
      { "phrase": "что ты думаешь", "replacements": ["чо думаешь", "нууу что думаешь", "скажи мне"], "probability": 0.29 },
      { "phrase": "я люблю", "replacements": ["я лууувлю", "обожаю", "просто люблюуу"], "probability": 0.36 },
      { "phrase": "это круто", "replacements": ["это круууто", "ваще огонь", "так секси"], "probability": 0.34 }
   ],
   sentence: {
      minWords: 4,
      insertions: [
         {
            position: "tail",
            minWords: 6,
            probability: 0.34,
            values: ["и все такое", "ну типа", "понимаешь"]
         },
         {
            position: "prefix",
            probability: 0.22,
            values: ["Ну ", "Короче, ", "Типа "]
         },
         {
            position: "beforeTag",
            tag: "adjective",
            probability: 0.24,
            values: ["прям", "вообще", "типа"]
         },
         {
            position: "afterTag",
            tag: "verb",
            probability: 0.2,
            values: ["как бы", "типа"]
         }
      ]
   },
   numberLabels: {
      many: "много"
   },
   wordTransform: {
      dictionaryProbability: 0.52,
      ruleProbability: 0.48
   },
   misspellRules: [
      { pattern: /тся\b|ться\b/g, replacement: "ца", probability: 0.6 },
      { pattern: /ого\b/g, replacement: "ова", probability: 0.38 },
      { pattern: /его\b/g, replacement: "ево", probability: 0.35 },
      { pattern: /чн/g, replacement: "шн", probability: 0.18 },
      { pattern: /сч/g, replacement: "щ", probability: 0.25 },
      { pattern: /жи/g, replacement: "жы", probability: 0.2 },
      { pattern: /ши/g, replacement: "шы", probability: 0.2 },
      { pattern: /нн/g, replacement: "н", probability: 0.25 },
      { pattern: /([аеёиоуыэюя])\1+/g, replacement: "$1", probability: 0.45 },

      // Новые правила (добавил 22 штуки)
      { "pattern": /что/g, "replacement": "чо", "probability": 0.55 },
      { "pattern": /почему/g, "replacement": "пачиму", "probability": 0.45 },
      { "pattern": /потому/g, "replacement": "патаму", "probability": 0.48 },
      { "pattern": /вообще/g, "replacement": "ваще", "probability": 0.5 },
      { "pattern": /сейчас/g, "replacement": "щас", "probability": 0.52 },
      { "pattern": /очень/g, "replacement": "очень", "probability": 0.25 },
      { "pattern": /очень/g, "replacement": "оч", "probability": 0.35 },
      { "pattern": /сегодня/g, "replacement": "севодня", "probability": 0.4 },
      { "pattern": /конечно/g, "replacement": "канешно", "probability": 0.45 },
      { "pattern": /извини/g, "replacement": "извен", "probability": 0.38 },
      { "pattern": /ладно/g, "replacement": "ладнооо", "probability": 0.4 },
      { "pattern": /([аеиоуюя])й\b/g, "replacement": "$1йй", "probability": 0.35 },
      { "pattern": /([аеёиоуыэюя])\b/g, "replacement": "$1аа", "probability": 0.28 },
      { "pattern": /([бвгджзклмнпрстфхцчшщ])\b/g, "replacement": "$1ь", "probability": 0.2 },
      { "pattern": /ка/g, "replacement": "каа", "probability": 0.3 },
      { "pattern": /ко/g, "replacement": "коо", "probability": 0.28 },
      { "pattern": /ку/g, "replacement": "куу", "probability": 0.3 },
      { "pattern": /то/g, "replacement": "тоо", "probability": 0.25 },
      { "pattern": /так/g, "replacement": "тааак", "probability": 0.4 },
      { "pattern": /как/g, "replacement": "кааак", "probability": 0.38 },
      { "pattern": /любл/g, "replacement": "лууубл", "probability": 0.35 },
      { "pattern": /хорош/g, "replacement": "хараш", "probability": 0.32 },
      { "pattern": /мил/g, "replacement": "миииил", "probability": 0.3 },
      { "pattern": /красив/g, "replacement": "красивеньк", "probability": 0.28 },
      { "pattern": /([аеио])ст/g, "replacement": "$1сь", "probability": 0.25 },
      { "pattern": /ый\b|ий\b/g, "replacement": "енький", "probability": 0.22 },
      { "pattern": /ая\b|яя\b/g, "replacement": "енькая", "probability": 0.2 }
   ],
   "words": {
      "вообще": ["ваще", "вобще"],
      "говорит": ["грит"],
      "говорю": ["грю"],
      "девушка": ["девчонка", "девачка"],
      "деньги": ["денги"],
      "думаю": ["думаю", "думаица"],
      "если": ["есле"],
      "здесь": ["тут", "здес"],
      "извините": ["извените", "сорян"],
      "интересно": ["интиресно"],
      "кажется": ["кажеца"],
      "конечно": ["канешно", "конешно"],
      "короче": ["кароче"],
      "красивый": ["красивенький", "красивый типа"],
      "лучше": ["лутше"],
      "меня": ["мя", "меня"],
      "мне": ["мну", "мне"],
      "может": ["можыт", "может типа"],
      "нельзя": ["низя"],
      "ничего": ["ничо", "ничево"],
      "нравится": ["нравица"],
      "окей": ["оки", "ок"],
      "очень": ["оч", "очень-преочень"],
      "пожалуйста": ["пж", "плиз"],
      "почему": ["пачиму"],
      "привет": ["превед", "приветик"],
      "примерно": ["премерно", "примерн"],
      "просто": ["прост", "проста"],
      "сейчас": ["щас", "ща"],
      "сегодня": ["севодня"],
      "серьезно": ["серьезна", "сириозна"],
      "сказать": ["сказать типа", "сказануть"],
      "спасибо": ["спс", "пасиба"],
      "тебя": ["тя", "тебя"],
      "теперь": ["типерь"],
      "тоже": ["тож"],
      "хорошо": ["харашо", "норм"],
      "хочу": ["хачу"],
      "человек": ["чел"],
      "через": ["чериз"],
      "что": ["што", "чо"],
      "чтобы": ["шоб"],
      "это": ["эта"],
      "этот": ["этат"],
      "компьютер": ["компьютир", "комп"],
      "библиотека": ["библеотека"],
      "разработка": ["разроботка"],
      "университет": ["универ"],
      "фотография": ["фотка"],
      "видео": ["видос"],
      "большой": ["огромный", "большой типа"],
      "любимый": ["любимый-прелюбимый"],
      "вероятно": ["наверн", "наверное"],
      "должен": ["должин"],
      "была": ["была типа"],
      "было": ["было типа"],
      "были": ["были типа"],
      "милый": ["миленький", "няшный"],
      "сексуальный": ["секси", "горячий", "сексуальненький"],
      "красивая": ["красотка", "красиваяя"],
      "девочка": ["девочкааа", "девчушка"]
   }
};
